name: 'Setup PureScript with Bun'
description: 'Install Node.js, Bun, PureScript, and Spago for CI builds'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '22'
  purescript-version:
    description: 'PureScript version to install'
    required: false
    default: '0.15.15'
  bun-version:
    description: 'Bun version to use'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Install PureScript compiler
      shell: bash
      run: bun install --global purescript@${{ inputs.purescript-version }}

    - name: Install Spago
      shell: bash
      run: bun install --global spago
